# Generated by Django 6.0.4 on 2026-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
