# Generated by Django 6.0.4 on 2026-06-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_department_id_alter_feedback_id_alter_issue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('confidential', 'Confidential')], default='public', max_length=20),
        ),
    ]
