# Generated by Django 5.2.13 on 2026-06-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_alter_department_id_alter_feedback_id_alter_issue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='issues.issue'),
        ),
    ]
