# Generated by Django 5.2.13 on 2026-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_is_duplicate_issue_merged_into'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuestatuslog',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], max_length=30),
        ),
    ]
