# Generated by Django 6.0.4 on 2026-06-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useractivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-login_time']},
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
