# Generated by Django 6.0.4 on 2026-06-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useractivitylog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOTP',
        ),
    ]
