# Generated by Django 6.0.4 on 2026-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('issue_submitted', 'Issue Submitted'), ('status_changed', 'Status Changed'), ('issue_assigned', 'Issue Assigned'), ('issue_resolved', 'Issue Resolved'), ('issue_rejected', 'Issue Rejected'), ('remark_added', 'Remark Added'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
